### ISSUE TITLE
Issues with CRUD

### ISSUE THREAD

**Issue by edwardyang12** [cse110-sp21-group9/cse110-sp21-group9#105]
- Adding bullet does not fill in "title" element 
- IDs in bulletIDs do not match what is being stored in local storage (some are not properly deleted etc.) 
- when delete is pressed with >=2 bullets in a category, bullets aren't updated to reflect changes except with refresh
- not all data are stored after a refresh
- unable to retag existing events
- number of tags does not match the number of tags entered
![image](https://user-images.githubusercontent.com/31996943/119415346-46011080-bca6-11eb-93ca-116070090741.png)

**Comment by alanlwang1** [comment]
Resolved by #141
